### ISSUE TITLE
Creating Project Plan

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#140]
### Problem Definition

In order to track our progress and finish the project on time, we need to prepare a project plan for the semester.

### Acceptance Criteria

The project plan should include a clear scope outline, realistic timelines, risk assessment, and a communication plan.

**Comment by YigitSekerci** [comment]
We had a discussion with @selinisik about this issue. While I am supporting making plan like we made last semester with timetable and task length, she wanted to make more generalized approach like below because of our lack of knowledge in task distribution and task split in the project. While both approach is have their upside we decided to ask this to our stakeholders before committing into one method. That's why there are some blanks in the plan for now. We will continue with this issue after the weekly meeting in the lab.

Current status of the plan is given below:

Creating a detailed project plan involves multiple steps, including defining the scope, setting goals, determining the stakeholders, defining tasks, and setting a timeline. Here's a high-level project plan for the semester:

1. Project Overview
Goal:
Develop a web and mobile platform where users can create and vote on polls. The platform will also have moderator features, a point system, and various user interactivity features.

2. Project Scope
In Scope:
- User registration and authentication.
- Creation and management of polls.
- Point system
- User profile management.
- Moderator functionality.
- Jury functionality.
- Leaderboard.
- Notifications.
- Security features.

Out of Scope:
- Addition of AI based solutions for moderation and jury tasks.

3. Stakeholders:
- Backend Developers
- Frontend Developers
- Mobile Developers

 4. Milestones and Major Tasks:

Milestone 1: Project Initialization
Tasks:
1. Gather team members and initiate kickoff meeting.
2. Revise requirements and diagrams.
3. Set up development, staging, and production environments.

 Milestone 2: Design & Prototyping
Tasks:
1. UI/UX design for all pages and functionalities.
2. Interactive mockup of all use cases to test whether the design covers all functions.

Milestone 3: Development - Phase 1 (Core Features)
Tasks:
1. User registration and authentication.
2. Poll creation and voting.
3. Point System
4. Profile management.

Milestone 4: Development - Phase 2 (Advanced Features)
Tasks:
1. Moderator features and functionality.
2. Jury features and functionality.
3. Leaderboard.
4. Notifications.
5. Search functionality.

Milestone 5: Testing 
Tasks:
--

Milestone 6: Deployment
Tasks:
1. Deploy to staging environment.
2. Quality assurance and bug fixing.
3. Deploy to production environment.

5. Resources:
- Development tools : IDE, github
- Project management tools: Github issues
- Testing tools ?
- Hosting and server resources ?
- Design tools: Figma

6. Timeline:
--

7. Risks:
--

8. Monitoring and Reporting:

Regular updates and check-ins will be provided to stakeholders, including:
- Weekly status updates.
- Milestone reports.
- Immediate notifications of any risks or challenges.

**Comment by YigitSekerci** [comment]
Created the first version of the mobile project plan will do adjustments after the requirements update tasks in following weeks.

**Comment by selinisik** [comment]
I have created the [frontend project plan](https://github.com/bounswe/bounswe2023group4/wiki/Frontend-Project-Plan). It may require some adjustments in the future.

**Comment by YigitSekerci** [comment]
We made our project plans for now. Even if there may be a need for improvements, we should open new issue for them. This issue is concluded.
