### ISSUE TITLE
Decide on what technologies are going to be used for the mobile

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#159]
### Problem Definition

We need to decide which products will be used in the mobile section of the project.

**Comment by aemresafak** [comment]
I have researched the mobile technologies used for Mobile programming:

For Android native development:
 - Java and View API
 - Kotlin and View API
 - Kotlin and Jetpack Compose
 
 For iOS native development:
 - Swift and UIKit
 - Swift and SwiftUI
 
 For cross-platform development:
 
 - Flutter
 - React Native
 - Kotlin Multiplatform for Mobile
 - Compose Multiplatform
 
 Since we will not be developing iOS application, I suggest that our team uses Kotlin and Jetpack Compose for android development. It is the state of the art for developing android apps and as far as I know our team has some experience with Jetpack Compose. Thus, I believe Kotlin and Jetpack Compose is the most suitable option for us.
 
 We can finalize this after your thoughts @YigitSekerci @AliAlperenSonmez

**Comment by YigitSekerci** [comment]
We can easily develop the project with the Kotlin + Jetpack compose since both me and @aemresafak knows it. Since compose structure similar to other frameworks even if @AliAlperenSonmez  doesn't know it, he can adapt it in no time. My vote is on Kotlin + Compose.

@AliAlperenSonmez what do you think?

**Comment by AliAlperenSonmez** [comment]
Based on my research, I found that Kotlin has a simpler syntax and is easier to learn. I believe this is the most important factor, because once we learn a technology, we can easily apply it to develop applications. Therefore, I will also go with:
# Kotlin and Jetpack Compose

**Comment by YigitSekerci** [comment]
Good so chosen tech: Kotlin + Jetpack Compose
