### ISSUE TITLE
Jury Selection (Req 1.1.4.8) Research

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#28]
### Problem Definition

We need to decide how to choose jury among users. Please discuss under this issue for possible solutions then update wiki.

### Problem Context

* Requirement 1.1.4.8

### Acceptance Criteria

* Discuss possible selections
* Update wiki

**Comment by EmreBatuhan** [comment]
As the application reaches more users we will probably need more people to monitor the increasing number of polls. I suggest a 2-rank system for this job. The first rank will be jury which can use the application like a user and remove the improper polls if some conditions are met. The second rank will be moderators which can do everything a jury can do plus, they can give users the jury or the moderator rank. 
Using this system the moderators can distribute jury role more safely because a malicious jury will not be as dangerous as a malicious moderator. And a safer distribution system will help growing our jury numbers.

**Comment by aemresafak** [comment]
#31 please check 31 for our solutions

**Comment by EmreBatuhan** [comment]
I think the system where a user that has 100000 points can be a moderator is limiting. I believe the system should accept the volunteer moderators that has below 100000 points. We should ask the 100000-point user to be a moderator rather than forcing them.

**Comment by selinisik** [comment]
I think the number of moderators should be calculated to be proportional to the number of polls. If the current number of moderators is less than this calculated number, we can open the voluntary moderator system.

**Comment by aemresafak** [comment]
> I think the number of moderators should be calculated to be proportional to the number of polls. If the current number of moderators is less than this calculated number, we can open the voluntary moderator system.

We discussed with @selinisik  and she mentioned that there will be no moderators when app is first published because no user will have 100000 points. That is a nice argument and brings up to my mind what @EmreBatuhan said. Maybe system should open volunteering requests to be moderator. To make sure there are always enough moderators, we can use a system like @selinisik  proposed whenever the proportion of polls to moderators is too high, the system should enable volunteering requests.

**Comment by enfurars** [comment]
Additionally, as a volunteering request to be a moderator comes from a user we can check some points like:
- Is the user is active or not? 
- Is user's previous poll's are suitable? 
(We need verifiable criteria for these)

**Comment by aemresafak** [comment]
This issue is closely related to #31. Selin and I have written requirements concerning this issue and #31 to the wiki page. Refer to #31 for more details. This requirements of this issue can be found in wiki page.
