### ISSUE TITLE
Jury Points (Req 1.2.2.2) Research

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#31]
### Problem Definition

Jury should be rewarded with points. Find a best reward system for both jury and project. Discuss under this issue and find a solution. Then update wiki. 

### Problem Context

* Requirement 1.2.2.2
* #28 

### Acceptance Criteria

* Find solution for jury rewards.
* Update wiki

### Suggested Solutions

#28 comments may help.

**Comment by EmreBatuhan** [comment]
I think the jury can recieve the entry fee that the poll opener paid. This question is also more meaningful with the question "what are the conditions for closing a poll?". Because we dont want to reward the juries that closed proper polls.

**Comment by AliNasra** [comment]
An issue here is whether a jury is picked from the user pool or not. If a jury can be also a user at the same time, I propose a 30% bonus from the poll's maximum point to the jury members. If the jury members are moderators, we don't need to consider this requirement.

**Comment by aemresafak** [comment]
There are **2 roles in the system.**
**User**: Regular people that use the app for voting and posting polls
**Moderator**: A moderator can do everything a user can do. Moreover, moderators can take part in _**juries**_. Each user can be a moderator if their points are above 100000. If a moderator does not fulfill his duty properly more than 5 times, their points are set to 1000, no matter how much points they currently have.
**Jury**: _Jury_ is a group of nine **_moderators_** that are responsible for **resolving a poll** and **investigating polls reported.**
**Gathering jury**: A jury of nine moderators is gathered in one of the following situations:
 - A poll has been reported by more than 250 unique users.
- A poll has ended and a finish request is sent to the system either by the system or the poll owner.
**Mechanism to gather the jury:**

1. System sends a **_join-the-jury request_** to all the moderators that have not participated in the poll that system needs help with. The **_INITIAL_** **prize** of the request for members of the jury is **%2** of the total points placed in the poll for each member of the jury.
2. If nine moderators accept the **_join-the-jury request_**, no other moderators can accept the request and the jury is now considered to be **gathered**. If a moderator tries to join a **gathered jury**, the system must show an error indicating that jury is already **gathered**.
3. If a jury of nine moderators could not be gathered after six hours, the system will again send request to all the moderators that have not participated in the corresponding poll. This time request has twice the prize compared to previous request.
4. This process is repeated until a jury is gathered.

**Resolving a poll**: 
1. When a poll ends, a finish request with a suggested answer is sent to the system. At this point, it is assumed that a jury has been gathered, if not repeat the steps _above_.  
2. Jury has 12 hours to resolve the poll. 
3. If the poll is subjective, jury members are encouraged to set the answer of the poll to the suggested answer. Otherwise, each jury must search the answer on the internet and set the answer of the poll.
4.  After twelve hours, if each jury member has set the correct answer, then the answer that has been set as true by most of the moderators is set to be **the answer** of the poll.
5. If one or more members of the jury has not set the answer to the poll after 12 hours, the jury is terminated and the members that did not set the answer in time are **punished by losing %2 of their total points**. Then, system repeats the process for gathering a jury and resolving the poll. 

**Investigating reports**:
1. When a poll has been reported by more than 250 unique users, a jury is gathered by steps described above.
2. Jury has 12 hours to resolve the poll. 
3. Each jury member investigates the reports. Then, they collectively decide what to do about it. (Report system must be elaborated for me to write proper requirements about it.)
5. If one or more members of the jury has not investigated the reports after the twelve hours, the jury is terminated and the members that did not set the answer in time are **punished by losing %2 of their total points**. Then, system repeats the process for gathering a jury and resolving the poll.

**Comment by EmreBatuhan** [comment]
I really like the gathering jury idea. I think the numbers can be changed. For example 12 hours might be too less for a jury. But the geenral concept is useful.
In this system a user that has 100000 points is kind of forced to be a moderator which I disagree. Also I see there is no motive behind being a moderator which may shrink our moderator numbers. This part of your system relates to issue [#28 jury selection](url) so lets continue this discussion there.

**Comment by selinisik** [comment]
- I think we can ask them to choose the most 5 tags they want to be a jury in and filter the requests according to these tags while sending them.
- They can change these tags whenever they want, and these tags are considered valid from the moment they are changed, and if there are requests that have come before, they still have to do it.

**Comment by aemresafak** [comment]
> * I think we can ask them to choose the most 5 tags they want to be a jury in and filter the requests according to these tags while sending them.
> * They can change these tags whenever they want, and these tags are considered valid from the moment they are changed, and if there are requests that have come before, they still have to do it.

I agree with you about moderators selecting tags. Certain moderators may not want to be a member of the jury of a poll about certain topic.

**Comment by EmreBatuhan** [comment]
> I agree that 12 hours may be too short. Maybe we can make it 24 hours. Moreover, I believe there are motivations to be a moderator and a jury, you get points by resolving polls, you help the community, you get to see many different results etc.

These are good motives, I see your point. We discussed how we will close the polls but we still need to decide how to distribute the points among the juries that resolved the poll. As suggested above by @AliNasra we can give a percentage of the total points paid by the voters or we can pay them the entry fee the poll opener paid.

**Comment by aemresafak** [comment]
Here is the revised version of the jury system:

There are 2 roles in the system.
User: Regular people that use the app for voting and posting polls. Users can apply for being a moderator.
Moderator: A moderator can do everything a user can do. Moreover, moderators can take part in juries. Each user can be a moderator if their points are above 100000. If a moderator does not fulfill his duty properly more than 5 times, their points are set to 1000, no matter how much points they currently have.  A moderator can choose at most 5 poll tags for the poll categories they are interested. Then, they can be a jury member for these 5 poll tags. System shall not send jury requests to moderators that are not interested in polls with certain tags.
Jury: Jury is a group of nine moderators that are responsible for resolving a poll and investigating polls reported.

**Volunteering as Moderator:**  Whenever active poll count divided by total number of moderators, i.e. number of polls per moderator, exceeds 15, system opens applications for volunteering as a moderator. Each user can volunteer. System will choose from the applicants. System will check for each user whether the user is active or not, the user has participated in more than 10 polls. If the user passes these two checks, first come first served algorithm will be applied and first applicants will be moderators.

Gathering jury: A jury of nine moderators is gathered in one of the following situations:

A poll has been reported by more than 250 unique users.
A poll has ended and a finish request is sent to the system either by the system or the poll owner.
Mechanism to gather the jury:
System sends a join-the-jury request to all the applicable (check above for what applicable means) moderators that have not participated in the poll that system needs help with. The INITIAL prize of the request for members of the jury is %2 of the total points placed in the poll for each member of the jury.
If nine moderators accept the join-the-jury request, no other moderators can accept the request and the jury is now considered to be gathered. If a moderator tries to join a gathered jury, the system must show an error indicating that jury is already gathered.
If a jury of nine moderators could not be gathered after six hours, the system will again send request to all the moderators that have not participated in the corresponding poll. This time request has twice the prize compared to previous request.
This process is repeated until a jury is gathered.
Resolving a poll:

When a poll ends, a finish request with a suggested answer is sent to the system. At this point, it is assumed that a jury has been gathered, if not repeat the steps above.
Jury has 12 hours to resolve the poll.
If the poll is subjective, jury members are encouraged to set the answer of the poll to the suggested answer. Otherwise, each jury must search the answer on the internet and set the answer of the poll.
After twelve hours, if each jury member has set the correct answer, then the answer that has been set as true by most of the moderators is set to be the answer of the poll.
If one or more members of the jury has not set the answer to the poll after 12 hours, the jury is terminated and the members that did not set the answer in time are punished by losing %2 of their total points. Then, system repeats the process for gathering a jury and resolving the poll.
Investigating reports:

When a poll has been reported by more than 250 unique users, a jury is gathered by steps described above.
Jury has 12 hours to resolve the poll.
Each jury member investigates the reports. Then, they collectively decide what to do about it. (Report system must be elaborated for me to write proper requirements about it.)
If one or more members of the jury has not investigated the reports after the twelve hours, the jury is terminated and the members that did not set the answer in time are punished by losing %2 of their total points. Then, system repeats the process for gathering a jury and resolving the poll.

**Comment by aemresafak** [comment]
###Glossary
Appropriate Moderator For A Poll:  Moderators who has selected at least one tag that the poll contains and that did not participated in the poll. If this condition is satisfied, the moderator can become a jury member for the poll.

### Users
1. If moderator applications are open, each user can send a request to the system to be a moderator.

### Moderator
1. Moderators shall be able to do whatever regular users do.
2. Moderators shall choose at least one at most five tags they are interested in. Tags chosen will be used by the system to determine which moderators can participate in a jury.
3. Moderators shall be able to accept or reject the active join-the-jury requests, explained in system requirements, they received.
3.1 Moderators shall participate in the jury for resolving a poll.
3.1.1. A moderator in a jury shall set the answer whatever he/she considers to be correct in 24 hours. 
3.1.2 If the poll the jury is responsible for is subjective, each jury member shall set the suggested answer as the correct answer.
3.1.3 Otherwise, each jury member shall do his/her own research and set his/her answer accordingly.
3.2 Moderators should participate in the jury investigating reports for a poll.
3.2.1 Each jury member shall vote for either delete the poll, not to delete the poll, or set the poll as finished.
4. Moderators shall not be able to accept passive join-the-jury requests. (Explained in system requirements)

### System Requirements
1. To gather a jury for a poll, the system shall send join-the-jury requests only to appropriate moderators (check glossary for definition).
2. The system shall send join-the-jury requests to appropriate moderators if the poll is reported by more than 250 unique users.
3. The system shall send join-the-jury requests to appropriate moderators if the poll has ended and a finish request is sent to the system either by the system or the poll owner.
5. The system must associate a prize with each join-the-jury request.
6. The system shall set the initial prize for each join-the-jury request to %2 of total points placed in the poll.
7. If nine moderators accept the join-the-jury request, the system shall set the join-the-jury requests for the same poll as passive.
8. If no nine moderators accept the join-the-jury request in six hours, the system shall send the join-the-jury request again to each appropriate moderator but this time with doubled prize. The system shall repeat this process until a jury of nine is gathered.
9. If jury does not answer the poll in time, System shall punish each jury member that did not set the correct answer or vote for the action to be taken by burning %10 of the points of the members aforementioned.
10. If jury does not answer the poll in time, the system shall send the join-the-jury request again to each appropriate moderator again but this time with doubled prize.
11. The system shall open moderator applications whenever total number of polls whose answer is not yet determined divided by the number of moderators is greater than fifteen.
12. The system shall promote users that applied for the moderatorship if they conform to two following criteria:
      - The user used the application in the 3 days past the date the application is being considered.
      - The user has participated in more than 10 polls either by posting them or voting for them.
13. After each promotion of user to moderator, the system shall close the application for moderatorship and reject all the remaining applications if total number of polls whose answer is not yet determined divided by the number of moderators is less than fifteen.

**Comment by aemresafak** [comment]
@selinisik as Selin mentioned, we have prepared the requirements and selin has written them down to the requirements wiki page. This finalizes the issue.
