### ISSUE TITLE
Requirements how to make point system meaningful

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#38]
### Problem Definition

We use point systems as currency in our application. However, this system alone does not encourage our users to use the application more. What can be done to make earning points more attractive?

### Acceptance Criteria

* Discuss possible solutions about promoting the point system
* Choose the best from the suggested solutions
* Consult the project owner on the selected result and get his approval

### Suggested Solutions

The point system can be supported with rewards and badges. As the number of rewards increases, some in-app priorities may be provided.

**Comment by aemresafak** [comment]
@EmreBatuhan makes great points at #35. Buying ranks can make points more meaningful. Please consider it.

**Comment by enfurars** [comment]
As I have stated at #35 earning a badge or things like that should be given automatically by the system which is more meaningful for the users I believe. Earned badges will be shown in their profile etc. However, I have also suggested to have fixed costs for opening a poll so maybe it seems like a conflict. Let me suggest what I think:

There will we two different point system. Cooler names can be found, these are only for better understanding.

**1. Domain Specific Point:**

These are the points that earned only from true predictions under a tag. They will be domain specific points belongs to a tag under which they are earned. They will be used to earn badges automatically by the system. These points will be deduced if the user makes a wrong guess. They are users' ranks indicating how good predictor a user is in a specific field. 

**2. General Point:**
  General points will consist of several points:

- x% of the points gained in all specific domains. (e.g. I have earned 100 points under football tag. I will earn 30 points as General points if  x = 30)
- Rewards of entering the platform daily/weekly etc.
- Will be used to open a poll in any domain with a fixed cost.
- Will be used to vote in a poll. 

**So domain specific points will serve to users as false sense of progress and mechanism of general points will give users the opportunity of using gained points. Additionally the inflation of general points is blocked by percentage gain from a poll and cost of opening a poll.**
- As a user as I signed up I will have some general points given by system and 0 points in all domains.
- I will keep getting general points as I enter the platform. 
- I can use my general points in polls belong to specific domains and get badges in that domain. Also I will have a rank in that domain.
- When I use my point to vote in a poll I will end up with less general points because of the percentage mechanism even if I predict correctly but in domain rank I will either earn or lose point according to my prediction. This system ensures there is no inflation of general points.
- I can use my general points to open polls. 
- I can show my domain specific badges and ranks that I want at my profile. 

Note: Negative points are not allowed. Minimum is 0.

**Comment by selinisik** [comment]
I think users can also use their points to customize their profile. For example, using their general points, they can buy animations, images or icons that will visually beautify their profile. Or, the images to be loaded in the thumbnail can be selected from certain options first and then asked for points to customize.

**Comment by selinisik** [comment]
I have updated the wiki page according to decided features. @EmreBatuhan can you check the subrequirement 1.1.7 .
