### ISSUE TITLE
API Research - YigitSekerci

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#79]
### Problem Definition

Every member needs to utilize at least one API as well as offer an API function.

### Acceptance Criteria

The API must be reviewed by the other team members.

**Comment by YigitSekerci** [comment]
I have chosen my api
# API-SPORTS
https://api-sports.io
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/56599776/235230071-e5f7cc3e-ad81-4545-839e-43fa4d0f18df.png">
* Good API for getting information about sports and even odds for games and races. Only drawback is that it is not free but since we don't need it for commercial usage it is good for our example project.
* I have used the some endpoints and I will show how to to use it at our next meeting.  
* In order to show how everything works in API, I have prepared Postman examples.

**Comment by YigitSekerci** [comment]
I have chosen my API can someone close my issue ??

**Comment by AliNasra** [comment]
Done
